const SpotifyActionTypes = {
    //GET token
        GET_TOKEN_FETCHING: 'GET_TOKEN_FETCHING',
        GET_TOKEN_SUCCESS: 'GET_TOKEN_SUCCESS',
        GET_TOKEN_FAILURE: 'GET_TOKEN_FAILURE',

    //logout
        LOGOUT_FETCHING: 'LOGOUT_FETCHING',
        LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
        LOGOUT_FAILURE: 'LOGOUT_FAILURE',

    //GET Track info
        GET_TRACK_INFO_FETCHING: 'GET_TRACK_INFO_FETCHING',
        GET_TRACK_INFO_SUCCESS: 'GET_TRACK_INFO_SUCCESS',
        GET_TRACK_INFO_FAILURE: 'GET_TRACK_INFO_FAILURE',
    
    //GET Current playback state
        GET_CURRENT_PLAYBACK_FETCHING: 'GET_TRACK_INFO_FETCHING',
        GET_CURRENT_PLAYBACK_SUCCESS: 'GET_TRACK_INFO_SUCCESS',
        GET_CURRENT_PLAYBACK_FAILURE: 'GET_TRACK_INFO_FAILURE',
}

export default SpotifyActionTypes;